export type Card = {
	id: number;
	nid: number;
	did: number;
	ord: number;
	mod: number;
	usn: number;
	type: 0 | 1 | 2 | 3;
	queue: -3 | -2 | -1 | 0 | 1 | 2 | 3;
	due: number;
	ivl: number;
	factor: number;
	reps: number;
	lapses: number;
	left: number;
	odue: number;
	odid: number;
	flags: number;
	data: string;
};
