import { NewSpreadValue } from '../dictionary/new-spread';

export type Configuration = Partial<{
	curDeck: number;
	activeDecks: number[];
	newSpread: NewSpreadValue;
	collapseTime: number;
	timeLim: number;
	estTimes: boolean;
	dueCounts: boolean;
	curModel: string;
	nextPos: number;
	sortType: string;
	sortBackwards: boolean;
	addToCur: boolean;
	dayLearnFirst: boolean;
	newBury: boolean;
	lastUnburied: number;
	activeCols: string[];
	question: string;
	answer: string;
	template: string;
	deck: string;
	noteFld: string;
	noteCrt: string;
	noteMod: string;
	cardMod: string;
	cardDue: string;
	cardIvl: string;
	cardEase: string;
	cardReps: string;
	cardLapses: string;
	noteTags: string;
	note: string;
}>;
